name: Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: 'compile'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5

      # Set up JDK 24
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: pom.xml

      # Build with Maven
      - name: Compile with Maven
        run: mvn compile -f pom.xml

