name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK 24
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: pom.xml

      - name: Verify JAVA_HOME
        run: |
          echo "JAVA_HOME is set to: $JAVA_HOME"

      # Run Maven tests
      - name: Run Maven Tests
        # This command will execute your project's tests.
        run: mvn test -f pom.xml
